### PR TITLE
[ENH] update collect_fmriprep.py

### LINKED ISSUE #10: MNI transform directory name in fmriprep workdir for collect_fmriprep() function?
I'm trying to gather files from my fmriprep work directory so that I can combine them, and continue pre-processing using collect_fmriprep.py, but it seems that my run of fmriprep20.1.1 did not generate those files - has the names of these directories possibly been changed in newer versions of fmriprep? 

It's possible that my run of fmriprep just didn't generate these files, but I think that's unlikely because my reports appear to be complete, and I didn't get any errors in my run. 

fMRIPrep command: 
```/usr/local/miniconda/bin/fmriprep /data /data/derivatives/fmriprep-20.1.1 participant --participant-label tst312 -w /work/ -vv --omp-nthreads 8 --nthreads 12 --mem_mb 30000 --output-spaces MNI152NLin2009cAsym:res-2 anat fsnative fsaverage5 --fs-subjects-dir /fsdir```

Thanks!

### PR DESCRIPTION
**Pull request by JulioAPeraza**
Fixes #10.

### Changes proposed in this pull request

- Generalize `collect_fmriprep.py` for multiple run/ses/task.

- Update to fMRIPrep `20.1.1` derivative and working directories.

- Collect partial preproc image and field warp when SDC is performed by fMRIPrep.

### CODE REVIEW

**Comment by JulioAPeraza** [comment]
@tsalo, I still need to change the first two elements of `XFORM_RENAME` to collect `scanner2T1w` transforms if freesurfer was omitted. I have not been able to run fmriprep to test this function.

**Comment by mckenziephagen** [comment]
I have runs of fMRIPREP with sdc corrections and freesurfer, and a few test sessions have run smoothly with the changes to collect_fmriprep.py from this PR. I might also have some runs without sdc and freesurfer, if you want to point me towards what information you need from those runs to complete this PR! I have a few questions/comments/suggestions: 

What is the rationale for doing the head motion corrections while gathering the files? For quality control purposes, I collect these files to run t2starmap on so that I can run mriqc on combined but otherwise unprocessed data, so maintaining data that is not hmced would be ideal. 

To achieve this, is it possible to merge the files globbed from `/bold_split/vol*.nii.gz` without doing head motion corrections so that they can be stored, optimally combined, and used quality control purposes, and separately gather the unmerged files and either do the hmc, or store them for hmc to be done in the same code with tedana denoising and other pre-processing steps? I'm likely to go this route in my local/forked version of collect_fmriprep.py, but if this is use case that others might be interested in, it might be apt to integrate it here as well. If this sounds reasonable, I can submit a PR with my changes to accomodate this use-case sometime this week.  

To avoid errors on future versions of fmriprep, could the code between line 89 and 107  be wrapped in a try/except, or if statement? 

Thanks, 
McKenzie

**Comment by JulioAPeraza** [comment]
> What is the rationale for doing the head motion corrections while gathering the files?

I collected those files just to do the HMC outside the working directory during the testing, in case I was breaking something.

> is it possible to merge the files globbed from /bold_split/vol*.nii.gz

Yes, I believe they can be merged with

```
merge = Merge(compress=True)
merge.inputs.in_files = files2merge
merge.run()
```

I think you could also take the files before `fslsplit` was run. They are located inside `bold_stc_wf`, which have been slice-timing-corrected. You could also use the data from your BIDS directory. 

Are you running the latest version of fMRIPrep? That version already collects the necessary transformation thanks to @tsalo [#2233](https://github.com/nipreps/fmriprep/pull/2233), so we only need the collect preprocessed echo-wise data. @tsalo also recommended simplifying the process and collect the motion-corrected + slice-timing-corrected + distortion-corrected volumes, instead of the current implementation: collect the motion-corrected + slice-timing-corrected volumes and field warp. The final function will look like this:

```python
def collect_fmriprep(deriv_dir, work_dir, subs):
    """
    Collect native-space preprocessed data from fMRIPrep working directory and
    copy into fMRIPrep derivatives directory, in BIDS format.

    Parameters
    ----------
    deriv_dir : str
    work_dir : str
    subs : list
        Cannot include sub- prefix.
    """
    for sub in subs:
        print("Wrangling subject {0}".format(sub))
        sub_in_dir = op.join(work_dir, "single_subject_{0}_wf".format(sub))
        task_dirs = glob(op.join(sub_in_dir, "func_preproc*_task_*_wf"))
        for task_dir in task_dirs:
            bb_wf_dir = op.join(task_dir, "bold_bold_trans_wf")
            bf_dirs = sorted(glob(op.join(bb_wf_dir, "_bold_file_*")))
            for bf_dir in bf_dirs:
                # Collect partially preprocessed data
                bf_dir_list = bf_dir.split("..")
                idx = bf_dir_list.index("sub-{0}".format(sub))
                sub_deriv_dir = op.join(deriv_dir, op.dirname("/".join(bf_dir_list[idx:])))
                bf_filename = bf_dir_list[-1]

                in_file = op.join(bf_dir, "merge", "vol0000_xform-00000_merged.nii.gz")

                # Conform output name
                orig_fn_list = bf_filename.split("_")
                fn_list = orig_fn_list[:]
                fn_list.insert(-1, "space-scanner")
                fn_list.insert(-1, "desc-partialPreproc")
                out_file = op.join(sub_deriv_dir, "_".join(fn_list))
                print("Writting {0}".format(out_file))
                copyfile(in_file, out_file)
```
In case someone is running an old version we can have `ORDER` and `XFORM_RENAME` as parameters and run the code between line `89` and `107` if those variables are not empty. Or simply, as you recommended, we can add an if statement and run those lines if the version is < `20.2.0`.
Does that help?

**Comment by mckenziephagen** [comment]
> I think you could also take the files before fslsplit was run. They are located inside bold_stc_wf, which have been slice-timing-corrected. 

Great, I'll write this option in. I think it makes more sense to use already combined files to cut down on time/computations, but this could be added in as a parameter (qc=False or something) so that if people don't want them, they can set that and avoid copying extra files. 

> Are you running the latest version of fMRIPrep? 

I am - but it doesn't output the sdc transform in the deriv_dir, right? 


>  @tsalo also recommended simplifying the process and collect the motion-corrected + slice-timing-corrected + distortion-corrected volumes, instead of the current implementation: collect the motion-corrected + slice-timing-corrected volumes and field warp.

Shouldn't distortion correction be done with the field warp after tedana is run? Which would involve collecting the un-hmced volumes that you implement in your PR, and applying hmc before running tedana. 

> In case someone is running an old version we can have ORDER and XFORM_RENAME as parameters and run the code between line 89 and 107 if those variables are not empty. Or simply, as you recommended, we can add an if statement and run those lines if the version is < 20.2.0.

Pass them as parameters to the function? Got it. 

> Does that help?

Yes, thank you!

**Comment by mckenziephagen** [comment]
One more note - it appears that using different fieldmap types gives you different filepaths to the transforms. I have directly measured fieldmaps ([option 2 in the fmriprep docs](https://fmriprep.org/en/stable/sdc.html)). I just checked the command.txt that you reference in issue #10 [here](https://github.com/ME-ICA/tedana-reliability-analysis/issues/10#issuecomment-668742541), and get `fmriprep_wf/single_subject_<...>_wf/func_preproc_ses_<...>_task_<...>_run_<...>_echo_1_wf/scd_estimate_wf/fmap2field_wf/vsm2dfm/sub-<...>_ses-<...>_run-<...>_fieldmap_merged_masked_recentered_filt_demean_maths_trans_rad_vsm_unmasked_desc-field_sdcwarp.nii.gz`. Any ideas on how this can be adapted, to be flexible for at least for these two types of fieldmaps? I was thinking check for both filepaths - `/sdc_estimate_wf/pepolar_unwarp_wf/` and `sdc_estimate_wf/fmap2field_wf` and adding whichever one exists to XFORM_RENAME would work nicely.

**Comment by JulioAPeraza** [comment]
> Shouldn't distortion correction be done with the field warp after tedana is run?

That was the initial idea of this pull request, but they ran a test on one dataset and distortion correction impacted all echoes equally.

> I was thinking check for both filepaths -` /sdc_estimate_wf/pepolar_unwarp_wf/` and `sdc_estimate_wf/fmap2field_wf` and adding whichever one exists to XFORM_RENAME would work nicely.

That will work, thanks!

@tsalo What do you think? Should we keep the SDC option open here in case someone wants to take that path, or should we merge this with the simplified code?

**Comment by tsalo** [comment]
> @tsalo What do you think? Should we keep the SDC option open here in case someone wants to take that path, or should we merge this with the simplified code?

I don't want to stand in anyone's way, but until there are analyses showing that SDC must be performed after combination/denoising, I would lean toward the simplified approach.

**Comment by mckenziephagen** [comment]
> That was the initial idea of this pull request, but they ran a test on one dataset and distortion correction impacted all echoes equally.

Oh, interesting! 

> I don't want to stand in anyone's way, but until there are analyses showing that SDC must be performed after combination/denoising, I would lean toward the simplified approach.

That seems fine. Are these planned analyses by the tedana team?  

@JulioAPeraza:  I think the paths you need for the first two entries in `XFORM_RENAME` are `bold_reg_wf/fsl_bbr_wf/fsl2itk_inv/affine.txt` and `bold_reg_wf/fsl_bbr_wf/fsl2itk_fwd/affine.txt` I grabbed these from fmriprep 20.1.2. 

Is that all that's needed to get this merged?

**Pull request merged**
